#! /bin/sh

bspc config border_width        3
bspc config window_gap          0

bspc config top_padding         15
bspc config focus_folows_pointer true
bspc config active_border_color "#220000"
bspc config focused_border_color "#FF0000"
bspc config presel_border_color "#000000"
bspc config urgent_border_color "#555555"
bspc config focused_locked_border_color "#FF0000"
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

$vga_monitor=`bspc query -M | grep VGA`
bspc monitor $vga_monitor -d WEB TODO
